### ISSUE TITLE
feat(pages/index): create FAQ section

### ISSUE THREAD

**Issue by selynna** [slohacks/slo-hacks-2019#4]
In FAQ.jsx, create:
- [x] Header.jsx (#7)
- [x] TextGroup.jsx (#10)

**Comment by mianuddin** [comment]
From what I can see in #22, this is missing some keys:
<img width="499" alt="screen shot 2018-10-04 at 14 13 13" src="https://user-images.githubusercontent.com/986543/46504089-b9963c80-c7e1-11e8-8667-7b7f7dc07fba.png">
